### ISSUE TITLE
Search Failure

### ISSUE THREAD

**Issue by proudsteel** [rubiety/jazzity#28]
When I started entering notes into the search bar I clicked one of the automagically generated entries that popped down. Once I clicked one of them I got an error page. This was due to the query string being entered into the get request with with spaces in between them. (Ex. http://jazzity.com/searches/C,%20Eb,%20Gb,%20Bb) where as "jazzity.com/searches/C,Eb,Gb,Bb" works just fine and redirects to "http://jazzity.com/chord-notes/C,Eb,Gb,Bb"

Just thought I'd help a fellow musician out.

Proudsteel

**Comment by eigenben** [comment]
Thanks! Fixed.
